const id = "policies/Committed Participant Agreement.md";
						const collection = "docs";
						const slug = "policies/committed-participant-agreement";
						const body = "\nThis agreement is entered into by and between the undersigned students (“Participants”) of\n(SIT374/SIT764 & SIT378/SIT782) at Thoth Tech (“Company”).\n\n## Objective\n\nThe main objective is to encourage collaboration among students who are eager to put in additional\nhours to generate an outstanding feature that can be referenced even after the completion of your\nstudies.\n\n## Commitments\n\n1. Time Dedication: Participants agree to collectively dedicate more hours per week to contribute to\n   the project.\n2. Regular Meetings: Participants agree to show up to team meetings on time to talk about the status\n   of the project, work through any obstacles, and plan how to develop it effectively.\n3. Task Distribution: Participants will be assigned specific roles and responsibilities based on\n   their skills and expertise. Each member pledges to do their assigned obligations within agreed\n   timeline.\n4. Communication: Effective and transparent communication is essential. Participants pledge to\n   communicate regularly through designated channels and respond promptly to team inquiries.\n5. Project Documentation: Thorough documentation of the project's requirement, roadmap, progress,\n   challenges, and solutions is essential. Participants agree to maintain detailed records and share\n   updates regularly.\n6. Quality Assurance: Participants commit to ensuring the highest quality of work. Regular testing\n   and quality checks will be conducted to meet or exceed Thoth Tech's standards.\n7. Duration: This agreement is effective from the day of signing and continues until the end of\n   trimester 3. Extensions may be discussed based on project requirements.\n\n## Consequences for Non-Compliance\n\n- Failure to adhere to the commitments outlined in this agreement may result in a re-evaluation of\n  the participant's involvement in the project.\n- Not fulfilling these obligations will lead to more severe grade penalties compared to students who\n  haven't agreed to this commitment.\n";
						const data = {title:"Committed Participant Agreement",editUrl:true,head:[],template:"doc",sidebar:{hidden:false,attrs:{}},pagefind:true};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/Danma/OneDrive/Desktop/Deakin-Work/Github Work/Capstone-Documentation-Website-Template/src/content/docs/policies/Committed Participant Agreement.md",
							rawData: "\ntitle: Committed Participant Agreement",
						};

export { _internal, body, collection, data, id, slug };
