const id = "products/company-operations/projects/docusaurus-documentation/Docusaurus Spike Outcome.md";
						const collection = "docs";
						const slug = "products/company-operations/projects/docusaurus-documentation/docusaurus-spike-outcome";
						const body = "\n==================\n\n**Spike:** Spike_No\n\n**Title:** Docusaurus Recommendation\n\n**Author:** Quinn Curtis, <xcurtis@deakin.edu.au>\n\n## Goals / Deliverables\n\nThe goal of this report was to determine if Docusaurus was a good option for Thoth Tech, and deliver\na spike with the answer\n\n## Technologies, Tools, and Resources used\n\n- Internet Browser (only tested with firefox and chrome)\n- NodeJS\n- Text Editor: VsCode\n- Terminal: Windows terminal\n- Programming Languages:\n  - JavaScript\n  - TypeScript\n  - React\n\n## Tasks undertaken\n\n- Ran Docusaurus and completed its setup and tutorial.\n- Was able to successfully add new pages and files to the site.\n- Research on the alternatives\n\n## What we found out\n\nDocusaurus provides a very simple, but intuitive solution to documentation. The install process is\nextremely simple thanks to Node.JS, and it is just as easy to create pages and custom content for\nthe platform.\n\nWhile there is still a large amount of work and research that will go into making an elegant\ntransition to the platform, the operations team believes that this is the best option. The other\noptions on the market were either too complex to get started, or were behind some form paywall.\nDocusaurus requires some knowledge of web-development, but is mostly a plug-and-play solution, with\na relatively easy flow to its tools and elements.\n\n## Open issues/risks\n\nThere was only one risk that was found over the course of this spike, and it is a small one at that.\nThere is very little documentation about the security of Docusaurus. However, it is a static site\ngenerator and there won't be any data stored on it that could put Thoth tech at risk, so this is\nonly a minor concern.\n\nPresently, there are a few open tasks that need to be undertaken by the team\n\n- Researching hosting options\n- Completing a site map\n- Designing the layout and content that should be on each page\n- Converting any relevant documentation to markdown to make the transition quicker and smoother.\n\n## Recommendations\n\nThe operations team recommends that Thoth tech moves forward with storing documentation on\nDocusaurus. It is very easy to use, and allows for quick generation of pages through the markdown\nfile format. Docusaurus would also make it easier to move over current documentation as Thoth tech\nalready uses .md for most documentation. We recommend using Docusaurus's default configuration for\nnow. If Typescript is deemed to be a better fit later down the line, we can always switch, but at\npresent the extra functionality it adds is unnecessary and would only add confusion.\n\nWe recommend getting started on the move ASAP to ensure that current and future team members can\ntake advantage of a better documentation engine than relying on github alone. Assigning team members\nto converting any current documentation should be a major priority, and site maps and designs should\nalso be produced.\n";
						const data = {title:"Docusaurus Spike Outcome",editUrl:true,head:[],template:"doc",sidebar:{hidden:false,attrs:{}},pagefind:true};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/Danma/OneDrive/Desktop/Deakin-Work/Github Work/Capstone-Documentation-Website-Template/src/content/docs/products/company-operations/projects/docusaurus-documentation/Docusaurus Spike Outcome.md",
							rawData: "\ntitle: Docusaurus Spike Outcome",
						};

export { _internal, body, collection, data, id, slug };
