const id = "products/company-operations/projects/docusaurus-documentation/Docusaurus Spike Plan.md";
						const collection = "docs";
						const slug = "products/company-operations/projects/docusaurus-documentation/docusaurus-spike-plan";
						const body = "\n==============\n\n**Name:**\n\nDocusaurus Recommendation plan\n\n## Context\n\nThe operations team needs to determine if Docusaurus is an appropriate tool for storing Thoth tech's\ndocumentation. It has been proposed as a better solution than just storing everything on the GitHub.\nThis spike outlines the steps needed to decide if this is the right solution for Thoth Tech.\n\n**Knowledge Gap:**\n\nany team members who are not familiar with docusaurus will need to be brought up to speed. Begin by\ngoing through the tool's documentation which can be found at:\n<https://docusaurus.io/docs/category/getting-started>\n\n**Skill Gap:**\n\nIf team members are not up to date with syntax and technologies used by docusaurus, begin\nup-skilling ASAP. W3 schools has great resources if you are unsure where to start.\n<https://www.w3schools.com/>\n\n**Technology Gap:**\n\nHosting and deployment need to be researched before we can deploy an instance of Docusaurus.\n\n## Goals/Deliverables\n\n- Create a list of reasons for Thoth tech to adopt Docusaurus, and any recommendations for using it.\n- Develop a basic test environment and some sample content.\n\n**Planned start date:** Week 2 T2 2023\n\n**Deadline:** The end of week 2 T2 2023\n\n## Planning notes\n\n- Begin by up-skilling in relevant areas. (if necessary) CSS, HTML, Javascript, React and Typescript\n  are the major ones.\n- Create a Docusaurus test environment to test its capabilities and drawbacks.\n- Get started with the Docusaurus docs page: <https://docusaurus.io/docs>\n- Draw up a mock layout of the Docusaurus structure further down the line. (design pages, folders\n  etc.)\n";
						const data = {title:"Docusaurus Spike Plan",editUrl:true,head:[],template:"doc",sidebar:{hidden:false,attrs:{}},pagefind:true};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/Danma/OneDrive/Desktop/Deakin-Work/Github Work/Capstone-Documentation-Website-Template/src/content/docs/products/company-operations/projects/docusaurus-documentation/Docusaurus Spike Plan.md",
							rawData: "\ntitle: Docusaurus Spike Plan",
						};

export { _internal, body, collection, data, id, slug };
