const id = "policies/Enthusiastic Participant Agreement.md";
						const collection = "docs";
						const slug = "policies/enthusiastic-participant-agreement";
						const body = "\n### Welcome aboard!\n\nWe're thrilled to have you on this journey. This agreement marks the collaborative spirit between\nyou - our enthusiastic participant – and Thoth Tech.\n\n### Our Objective:\n\nOur aim is to create an environment where enthusiastic participants can invest extra hours, blending\ncreativity and expertise to craft something truly exceptional. This project isn't just about grades;\nit's an opportunity to create something you will be proud of long after your studies.\n\n### Commitments:\n\n1. <b>Time Commitment</b>: We agree to dedicating additional time, bringing our best efforts to the\n   table each week.\n2. <b>Regular Meetings</b>: We’ll meet consistently and promptly to discuss progress, address\n   challenges, and plan our collective next steps.\n3. <b>Task Allocation</b>: Leveraging our unique strengths, we'll assign roles that match our skills\n   and trust each other to effectively fulfill these roles within set timelines.\n4. <b>Open Communication</b>: Transparent and responsive communication remains essential. We’ll stay\n   in touch regularly through our preferred channels.\n5. <b>Documenting the Journey</b>: Maintaining a record of our project’s journey is vital. We'll\n   document requirements, track progress, and shares updates along the way.\n6. <b>Quality Assurance</b>: Quality is non-negotiable. Regular checks and reviews will ensure our\n   work meets Thoth Tech’s high standards.\n7. <b>Duration</b>: This agreement is effective from the moment we sign it and will go on until the\n   end of trimester 3. If needed, extensions may be discussed depending on project’s requirements.\n\n### If Things Don't Go as Planned:\n\nWe understand that life happens. If sticking to these commitments becomes challenging, let’s talk\nand find a solution together. No penalties – just support.\n\n### Let's Get Started!\n\nThis isn't just an agreement; it’s our commitment to collaborate and create something phenomenal.\nLet’s kick-start this journey together!\n";
						const data = {title:"Enthusiastic Participant Agreement",editUrl:true,head:[],template:"doc",sidebar:{hidden:false,attrs:{}},pagefind:true};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/Danma/OneDrive/Desktop/Deakin-Work/Github Work/Capstone-Documentation-Website-Template/src/content/docs/policies/Enthusiastic Participant Agreement.md",
							rawData: "\ntitle: Enthusiastic Participant Agreement",
						};

export { _internal, body, collection, data, id, slug };
