const id = "products/ontrack/documentation/numbas/Numbas Feasibility Check.md";
						const collection = "docs";
						const slug = "products/ontrack/documentation/numbas/numbas-feasibility-check";
						const body = "\n**Daniel Maddern**.\n\n**Capstone SIT374**.\n\n**Ontrack**.\n\n**Numbas feasibility check**.\n\n**Preamble**.\n\nThe aim of this study is to check the feasibility of setting up or linking Numbas into Ontrack a\nlive production environment running on Rails/Angular.\n\n**Research information**:\n\nFor this project I have been reviewing several links and pages of information to ensure we take the\ncorrect direction. As well as to upskill to ensure I have the key skills required for this project.\n\n[https://angular.io/guide/standalone-components](https://angular.io/guide/standalone-components)\n\n[https://blog.logrocket.com/the-ultimate-guide-to-iframes/](https://blog.logrocket.com/the-ultimate-guide-to-iframes/)\n\n[https://angular.io/guide/setup-local](https://angular.io/guide/setup-local)\n\n[https://www.numbas.org.uk/](https://www.numbas.org.uk/)\n\n[https://community.dataminer.services/information-security-research-unsafe-attribute-bindings-on-iframe-elements-in-angular/](https://community.dataminer.services/information-security-research-unsafe-attribute-bindings-on-iframe-elements-in-angular/)\n\n**Outcome**.\n\nSo after some research the two main ways we can approach this task is to embed an iframe, then later\ncapture the test objecet and store it.\n\nOr we can use the local NPM package and install Numbas as a package and configure and run the tests\nnatively.\n\nThe second option initially looks more secure and longer to setup, I was concerned about iFrame from\na security risk related to XSS, however it looks like in Angular 15 this was resolved.\n\n**Plan**.\n\nI will look at configuring both solutions and see which one performs best and gives us the best\nfeatures moving forward. Hopefully by week 6 a have a trial version of both and make the final\ndecision before tidying up the code to ensure it is production ready.\n";
						const data = {title:"Project feasability study document",editUrl:true,head:[],template:"doc",sidebar:{hidden:false,attrs:{}},pagefind:true};
						const _internal = {
							type: 'content',
							filePath: "C:/Users/Danma/OneDrive/Desktop/Deakin-Work/Github Work/Capstone-Documentation-Website-Template/src/content/docs/products/ontrack/documentation/numbas/Numbas Feasibility Check.md",
							rawData: "\ntitle: Project feasability study document",
						};

export { _internal, body, collection, data, id, slug };
